apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bandung-coffeeshop-be.yaml
  - bandung-coffeeshop-fe.yaml
#  - bandung-coffeeshop-image.yaml
#  - job-scraper-bot.yaml
#  - job-scraper-mcp.yaml
  - kawan-ngonser-be.yaml
  - kawan-ngonser-fe.yaml
  - ofgs-api.yaml
#  - postgres-backup-r2.yaml
#  - sinan-gotth-finance.yaml
#  - sinan-portfolio.yaml
#  - skripsi.yaml
  - split-bill-be.yaml
#  - tiketin-v2-be.yaml
#  - tiketin-v2-fe.yaml
#  - vern.yaml
