apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vern
  namespace: flux-system
spec:
  image: ghcr.io/pt-sinan-akbar/vern
  interval: 10m
  secretRef:
    name: flux-registry-creds
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vern
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vern
  filterTags:
    pattern: '^(?P<ts>[0-9]+)-[0-9a-f]{7}$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
