apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prod
  name: sinan-gotth-finance-backup-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
