apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: bandung-coffeeshop-be-config
    namespace: dev
    envs: [bandung-coffeeshop-be.env]
  - name: bandung-coffeeshop-fe-config
    namespace: dev
    envs: [bandung-coffeeshop-fe.env]
