apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: prod
  name: job-scraper-bot
spec:
  schedule: "0 8,20 * * *"
  timeZone: "Asia/Jakarta"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: node_type
                        operator: In
                        values:
                          - high-availability
          containers:
            - name: job-scraper-bot
              image: ghcr.io/pt-sinan-akbar/job-scraper-bot:ab3ab6f8
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - /workspace/scraper-bot/cron/run-scraper.sh
              envFrom:
                - configMapRef:
                    name: job-scraper-config
                - secretRef:
                    name: job-scraper-secret
          restartPolicy: OnFailure
