apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-app
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/DTA32/flux-gitops   # must be HTTPS, not ssh://
  ref:
    branch: master
  provider: github
  secretRef:
    name: flux-github-app
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system-app
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: 190590078+dta32-homeserver[bot]@users.noreply.github.com
        name: dta32-homeserver[bot]
      messageTemplate: |
        chore(images): automated tag bump

        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
    push:
      branch: master
  update:
    path: ./
    strategy: Setters
